### PR TITLE
Homepage now shows 'No active channels at the moment' if there isn't.

### PR DESCRIPTION
**Pull request by Pyyret**
Homepage now shows 'No active channels at the moment' if there isn't.

### CODE REVIEW

**Review by ShinzenATT — CHANGES_REQUESTED** [review]
the homepage still loads indefinitely so the message is unlikely to appear, maybe a timeout is needed when getting the channels?

**Comment by Pyyret** [comment]
> the homepage still loads indefinitely so the message is unlikely to appear, maybe a timeout is needed when getting the channels?

Hmm, this does not happen for me. Is it because you dont have a server running?

**Review by ShinzenATT — DISMISSED** [review]
I debugged it further and found that the dbServer doesn't make a request when there are no channels so changing it so it returns an empty list made the loading stop.

**Review by Anaemix — APPROVED** [review]
Looks good

**Pull request merged**
